package com.sunrise.dental.model;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

public class Appointment {

    private String apptNumber;
    private Patient patient;
    private Dentist dentist;
    private String treatment;
    private LocalDate apptDate;
    private LocalTime apptTime;
    private String status = "CONFIRMED";

    private static final LocalTime CLINIC_OPEN = LocalTime.of(9, 0);
    private static final LocalTime CLINIC_CLOSE = LocalTime.of(17, 0);

    public Appointment() {
    }

    public Appointment(Patient patient, Dentist dentist, String treatment,
                        LocalDate apptDate, LocalTime apptTime) {
        this.patient = patient;
        this.dentist = dentist;
        this.treatment = treatment;
        this.apptDate = apptDate;
        this.apptTime = apptTime;
    }

    /**
     * Appointment numbers are generated by AppointmentDAOImpl at insert
     * time (format "APT-0001", incrementing from the highest existing
     * number in the table) — the same approach as BillDAO.generateNextBillId().
     * This method isn't needed on the model itself since generation needs
     * a database connection to find the last-used number.
     */

    /**
     * Validates this appointment's fields before it's saved. Checks:
     *  - patient name, address, contact aren't blank
     *  - contact is exactly 10 digits
     *  - appointment date is not in the past
     *  - appointment time is within clinic hours (9am-5pm)
     * Returns true if valid. Call getValidationErrors() first (or after a
     * false result) to see what failed.
     */
    private List<String> validationErrors = new ArrayList<>();

    public boolean validate() {
        validationErrors.clear();

        if (patient == null) {
            validationErrors.add("Patient details are required.");
        } else {
            if (isBlank(patient.getName())) {
                validationErrors.add("Patient name cannot be blank.");
            }
            if (isBlank(patient.getAddress())) {
                validationErrors.add("Patient address cannot be blank.");
            }
            if (isBlank(patient.getContact())) {
                validationErrors.add("Patient contact cannot be blank.");
            } else if (!patient.getContact().matches("\\d{10}")) {
                validationErrors.add("Patient contact must be exactly 10 digits.");
            }
        }

        if (apptDate == null) {
            validationErrors.add("Appointment date is required.");
        } else if (apptDate.isBefore(LocalDate.now())) {
            validationErrors.add("Appointment date cannot be in the past.");
        }

        if (apptTime == null) {
            validationErrors.add("Appointment time is required.");
        } else if (apptTime.isBefore(CLINIC_OPEN) || apptTime.isAfter(CLINIC_CLOSE)) {
            validationErrors.add("Appointment time must be between 9:00 AM and 5:00 PM.");
        }

        return validationErrors.isEmpty();
    }

    public List<String> getValidationErrors() {
        return validationErrors;
    }

    private boolean isBlank(String s) {
        return s == null || s.trim().isEmpty();
    }

    public String getDetails() {
        return "Appointment #" + apptNumber
                + " | Patient: " + (patient != null ? patient.getName() : "N/A")
                + " | Dentist: " + (dentist != null ? dentist.getName() : "N/A")
                + " | Treatment: " + treatment
                + " | Date: " + apptDate
                + " | Time: " + apptTime
                + " | Status: " + status;
    }

    public String getApptNumber() {
        return apptNumber;
    }

    public void setApptNumber(String apptNumber) {
        this.apptNumber = apptNumber;
    }

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public Dentist getDentist() {
        return dentist;
    }

    public void setDentist(Dentist dentist) {
        this.dentist = dentist;
    }

    public String getTreatment() {
        return treatment;
    }

    public void setTreatment(String treatment) {
        this.treatment = treatment;
    }

    public LocalDate getApptDate() {
        return apptDate;
    }

    public void setApptDate(LocalDate apptDate) {
        this.apptDate = apptDate;
    }

    public LocalTime getApptTime() {
        return apptTime;
    }

    public void setApptTime(LocalTime apptTime) {
        this.apptTime = apptTime;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}
